# Generated by Django 5.0.2 on 2024-05-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ahe_mb', '0023_alter_sitedevice_site_device_conf'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SimulatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=5000)),
                ('map_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.map')),
            ],
        ),
        migrations.CreateModel(
            name='TestExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=50)),
                ('epoch', models.IntegerField()),
                ('test_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sim.testscenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('function', models.CharField(choices=[('less_than', 'less_than'), ('less_than_equal_to', 'less_than_equal_to'), ('greater_than', 'greater_than'), ('greater_than_equal_to', 'greater_than_equal_to'), ('equal_to', 'equal_to'), ('not_equal_to', 'not_equal_to')], default='equal_to', max_length=50)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.field')),
                ('test_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sim.testscenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('initial_value', models.FloatField()),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.field')),
                ('test_scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sim.testscenario')),
            ],
        ),
    ]
