# Generated by Django 5.0.2 on 2024-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariooutput',
            name='initial_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scenarioinput',
            name='initial_value',
            field=models.FloatField(default=0),
        ),
    ]
