# Generated by Django 5.0.2 on 2024-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testscenario',
            old_name='time_out',
            new_name='timeout',
        ),
        migrations.AddField(
            model_name='scenariooutput',
            name='initial_function',
            field=models.CharField(choices=[('less_than', 'less_than'), ('less_than_equal_to', 'less_than_equal_to'), ('greater_than', 'greater_than'), ('greater_than_equal_to', 'greater_than_equal_to'), ('equal_to', 'equal_to'), ('not_equal_to', 'not_equal_to')], default='equal_to', max_length=50),
        ),
        migrations.AlterField(
            model_name='scenarioinput',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='scenariooutput',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
