# Generated by Django 5.0.2 on 2024-05-23 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sim', '0002_rename_time_out_testscenario_timeout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioinput',
            name='test_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='ahe_sim.testscenario'),
        ),
        migrations.AlterField(
            model_name='scenariooutput',
            name='test_scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='ahe_sim.testscenario'),
        ),
    ]
