# Generated by Django 5.0.2 on 2024-05-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0023_alter_sitedevice_site_device_conf'),
        ('ahe_sim', '0003_alter_scenarioinput_test_scenario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScenarioInput',
            new_name='Input',
        ),
        migrations.RenameModel(
            old_name='ScenarioOutput',
            new_name='Output',
        ),
    ]
