# Generated by Django 5.0.2 on 2024-05-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0023_alter_sitedevice_site_device_conf_and_more'),
        ('ahe_sim', '0004_alter_input_device_alter_output_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='variable',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.field'),
        ),
    ]
