# Generated by Django 5.0.2 on 2024-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sim', '0002_input_device_output_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='function',
            field=models.CharField(choices=[('less_than', 'less_than'), ('less_than_equal_to', 'less_than_equal_to'), ('greater_than', 'greater_than'), ('greater_than_equal_to', 'greater_than_equal_to'), ('equal_to', 'equal_to'), ('not_equal_to', 'not_equal_to')], default=None, max_length=50),
        ),
    ]
