# Generated by Django 5.0.2 on 2024-06-13 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0023_alter_sitedevice_site_device_conf_and_more'),
        ('ahe_sim', '0006_testscenario_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_power_mode', models.FloatField(default=7)),
                ('charging_active_power', models.FloatField(default=-1)),
                ('discharging_active_power', models.FloatField(default=1)),
                ('connected_devices', models.ManyToManyField(blank=True, default=None, related_name='plc_connected_devices', to='ahe_mb.sitedevice')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plc_name', to='ahe_mb.sitedevice')),
            ],
        ),
    ]
