# Generated by Django 5.0.2 on 2024-06-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0023_alter_sitedevice_site_device_conf_and_more'),
        ('ahe_sim', '0007_plc'),
    ]

    operations = [
        migrations.AddField(
            model_name='plc',
            name='active_power_variable',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.field'),
        ),
    ]
