# Generated by Django 4.2.6 on 2023-11-16 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ahe_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config_type', models.CharField(blank=True, max_length=20, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.site')),
            ],
        ),
        migrations.CreateModel(
            name='Hirarchy',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeyMap',
            fields=[
                ('var', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pattern', models.CharField(blank=True, max_length=50, null=True)),
                ('has_variables', models.BooleanField()),
                ('count', models.IntegerField()),
                ('hirarchy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_translate.hirarchy')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahe_translate.node')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
                ('func', models.CharField(max_length=50)),
                ('removed_match', models.BooleanField(default=False)),
                ('param', models.CharField(blank=True, max_length=50, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_translate.config')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahe_translate.translation')),
            ],
        ),
        migrations.CreateModel(
            name='NodeVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahe_translate.node')),
            ],
        ),
    ]
