# Generated by Django 4.2.6 on 2023-11-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('A', 'activePowerMode'), ('R', 'reactivePowerMode')], max_length=100)),
                ('mode_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_category', models.CharField(choices=[('aircon', 'Air conditioner'), ('aux', 'Aux'), ('battery', 'Battery'), ('co_sensor', 'Co_sensor'), ('common_acdb', 'Common acdb'), ('dc_meter', 'DC meter'), ('ems', 'Ems'), ('ess', 'Ess'), ('grid', 'Grid'), ('humidity', 'Humidity sensor'), ('inverter', 'Inverter'), ('load', 'Load'), ('ppi_analog', 'Ppi analog'), ('pv', 'PV'), ('rack', 'Rack'), ('temp_controller', 'Temperature Controller'), ('temp_scanner', 'Temperature Scanner'), ('bm_bank', 'Bm bank'), ('battery__module', 'Battery Module'), ('battery__string', 'Battery String')], max_length=50)),
                ('interface_type', models.CharField(choices=[('MODBUS', 'MODBUS'), ('OPC', 'OPC')], default='MODBUS', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('M', 'Med Name'), ('L', 'Long Name'), ('R', 'Required in frontend'), ('D', 'Decimal Places'), ('U', 'Measurement Unit')], max_length=1)),
                ('pattern', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('mode_type', models.CharField(choices=[('S', 'slider'), ('T', 'time'), ('H', 'scheduler'), ('O', 'select_options')], max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=50)),
                ('max_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('read_var_name', models.CharField(max_length=100)),
                ('write_var_name', models.CharField(max_length=100)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.allowedmode')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SiteDeviceConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.site')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('med_name', models.CharField(default='', max_length=100)),
                ('long_name', models.CharField(default='', max_length=100)),
                ('require_in_frontend', models.BooleanField(default=False)),
                ('measurement_unit', models.CharField(default='', max_length=30)),
                ('decimal_places', models.IntegerField(default=2)),
                ('category', models.CharField(choices=[('Main', 'Main'), ('Cell', 'Cell'), ('Alarm', 'Alarm'), ('Status', 'Status')], default='Main', max_length=30)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.devicetype')),
                ('site_device_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.sitedeviceconf')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMetaConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.sitemeta')),
                ('site_meta_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.sitemetaconf')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.devicetype')),
                ('site_device_conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.sitedeviceconf')),
            ],
        ),
        migrations.CreateModel(
            name='ModeInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('input', models.CharField(max_length=50)),
                ('mode_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.modeinput')),
            ],
        ),
        migrations.AddField(
            model_name='allowedmode',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.site'),
        ),
    ]
