# Generated by Django 4.2.6 on 2023-11-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0002_alter_sitedevice_site_device_conf_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sitemeta',
            unique_together={('site_meta_conf', 'key', 'parent')},
        ),
    ]
