# Generated by Django 4.2.6 on 2023-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0003_alter_sitemeta_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemeta',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
