# Generated by Django 4.2.6 on 2023-11-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0005_sitevariableconf_alter_variable_site_device_conf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='site_device_conf',
            new_name='site_variable_conf',
        ),
        migrations.AlterField(
            model_name='variable',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.devicetype'),
        ),
    ]
