# Generated by Django 4.2.6 on 2023-11-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0006_rename_site_device_conf_variable_site_variable_conf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedevice',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
