# Generated by Django 4.2.6 on 2023-11-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0008_rename_sitedeviceconf_sitedevicelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='sitedevice',
            old_name='site_device_conf',
            new_name='site_device',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
