# Generated by Django 4.2.6 on 2023-11-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0009_deviceconf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceConf',
        ),
    ]
