# Generated by Django 4.2.6 on 2023-11-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0010_delete_deviceconf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedevice',
            name='site_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_list', to='ahe_sys.sitedevicelist'),
        ),
    ]
