# Generated by Django 4.2.6 on 2023-11-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0011_alter_sitedevice_site_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteDevice',
        ),
    ]
