# Generated by Django 5.0.1 on 2024-01-25 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0014_keymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemeta',
            name='site_meta_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ahe_sys.sitemetaconf'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='site_variable_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ahe_sys.sitevariablelist'),
        ),
    ]
