# Generated by Django 5.0.1 on 2024-01-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0015_alter_sitemeta_site_meta_conf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyMap',
        ),
    ]
