# Generated by Django 5.0 on 2024-02-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0017_varmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='AheClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_site_id', models.IntegerField(default=0)),
                ('end_site_id', models.IntegerField(default=0)),
            ],
        ),
    ]
