# Generated by Django 5.0 on 2024-02-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0018_aheclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.aheclient'),
            preserve_default=False,
        ),
    ]
