# Generated by Django 5.0 on 2024-02-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0019_site_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='device_category',
            field=models.CharField(choices=[('aircon', 'Air conditioner'), ('aux', 'Aux'), ('battery', 'Battery'), ('co_sensor', 'Co_sensor'), ('common_acdb', 'Common acdb'), ('dc_meter', 'DC meter'), ('ems', 'Ems'), ('ess', 'Ess'), ('grid', 'Grid'), ('humidity', 'Humidity sensor'), ('inverter', 'Inverter'), ('load', 'Load'), ('ppi_analog', 'Ppi analog'), ('pv', 'PV'), ('rack', 'Rack'), ('temp_controller', 'Temperature Controller'), ('temp_scanner', 'Temperature Scanner'), ('bank', 'bank'), ('cell', 'Cell'), ('module', 'Module'), ('string', 'String')], max_length=50),
        ),
    ]
