# Generated by Django 5.0.3 on 2024-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_sys', '0020_alter_devicetype_device_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='uuid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
