# Generated by Django 4.2.6 on 2023-11-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ahe_sys', '0006_rename_site_device_conf_variable_site_variable_conf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Enum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('map_reg', models.CharField(choices=[('Coil', 'Coil'), ('Discrete Input', 'Discrete Input'), ('Input Register', 'Input Register'), ('Holding Register', 'Holding Register')], default='Holding Register', max_length=50)),
                ('map_max_read', models.IntegerField(default=120)),
                ('read_spaces', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='ModbusDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('start_address', models.IntegerField()),
                ('data_hold_period', models.IntegerField(default=60)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ahe_mb.map')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.site')),
            ],
        ),
        migrations.CreateModel(
            name='ModbusMapEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('func', models.CharField(max_length=50)),
                ('variable', models.CharField(max_length=100)),
                ('param', models.FloatField()),
                ('level', models.CharField(default='warning', max_length=20)),
                ('status', models.CharField(default='Disable', max_length=20)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.modbusdevice')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.map')),
            ],
            options={
                'unique_together': {('map', 'device', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('field_address', models.IntegerField()),
                ('field_encoding', models.CharField(choices=[('', ''), ('Big-endian', 'Big-endian'), ('Little-endian', 'Little-endian'), ('Big-endian byte swap', 'Big-endian byte swap'), ('Little-endian byte swap', 'Little-endian byte swap')], default='', max_length=30)),
                ('field_format', models.CharField(choices=[('bitmap', 'bitmap'), ('boolean', 'boolean'), ('string', 'string'), ('array', 'array'), ('uint16', 'uint16'), ('sint16', 'sint16'), ('uint32', 'uint32'), ('sint32', 'sint32'), ('float32', 'float32')], max_length=20)),
                ('field_scale', models.FloatField(default=1)),
                ('field_offset', models.FloatField(default=0)),
                ('field_size', models.IntegerField(default=0)),
                ('measure_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('bit_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahe_mb.bitmap')),
                ('enum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ahe_mb.enum')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.map')),
            ],
            options={
                'unique_together': {('map', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EnumValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahe_name', models.CharField(max_length=250)),
                ('value', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('enum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_values', to='ahe_mb.enum')),
            ],
            options={
                'unique_together': {('enum', 'ahe_name')},
            },
        ),
        migrations.CreateModel(
            name='BitValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahe_name', models.CharField(max_length=250)),
                ('start_bit', models.IntegerField()),
                ('end_bit', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('bit_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bit_values', to='ahe_mb.bitmap')),
            ],
            options={
                'unique_together': {('bit_map', 'ahe_name')},
            },
        ),
    ]
