# Generated by Django 4.2.6 on 2023-11-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0002_alter_bitvalue_bit_map_alter_enumvalue_enum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='ahe_name',
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=set(),
        ),
    ]
