# Generated by Django 4.2.6 on 2023-11-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0003_rename_name_field_ahe_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='ahe_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
