# Generated by Django 5.0 on 2023-12-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0005_remove_map_device_type_devicemap_deviceconf'),
        ('ahe_sys', '0013_rename_sitevariableconf_sitevariablelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ahe_sys.devicetype'),
        ),
    ]
