# Generated by Django 5.0 on 2023-12-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0006_map_device_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceMap',
        ),
    ]
