# Generated by Django 5.0 on 2023-12-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0007_delete_devicemap'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modbusmapevents',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modbusmapevents',
            name='device',
        ),
        migrations.RemoveField(
            model_name='modbusmapevents',
            name='map',
        ),
        migrations.DeleteModel(
            name='DeviceConf',
        ),
        migrations.DeleteModel(
            name='ModbusMapEvents',
        ),
    ]
