# Generated by Django 5.0 on 2023-12-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0008_alter_modbusmapevents_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModbusDevice',
        ),
    ]
