# Generated by Django 5.0 on 2023-12-18 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0009_delete_modbusdevice'),
        ('ahe_sys', '0013_rename_sitevariableconf_sitevariablelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('unit', models.IntegerField()),
                ('data_hold_period', models.IntegerField(default=60)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.devicetype')),
                ('site_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_device', to='ahe_sys.sitedevicelist')),
            ],
        ),
        migrations.CreateModel(
            name='SiteModbusDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_sys.site')),
            ],
        ),
    ]
