# Generated by Django 5.0 on 2023-12-18 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0010_device_sitemodbusdevices'),
        ('ahe_sys', '0013_rename_sitevariableconf_sitevariablelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteModbusDevices',
            new_name='SiteModbusDevicesConf',
        ),
        migrations.RemoveField(
            model_name='device',
            name='site_device',
        ),
        migrations.AddField(
            model_name='device',
            name='site_device_conf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_device_conf', to='ahe_mb.sitemodbusdevicesconf'),
            preserve_default=False,
        ),
    ]
