# Generated by Django 5.0 on 2023-12-18 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0011_rename_sitemodbusdevices_sitemodbusdevicesconf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='site_device_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ahe_mb.sitemodbusdevicesconf'),
        ),
    ]
