# Generated by Django 5.0 on 2023-12-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0012_alter_device_site_device_conf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='name',
        ),
    ]
