# Generated by Django 5.0 on 2023-12-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0013_rename_device_name_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='start_address',
            field=models.IntegerField(default=0),
        ),
    ]
