# Generated by Django 5.0 on 2023-12-27 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0015_devicemodifierconf_mapmodifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='start_address',
        ),
        migrations.RemoveField(
            model_name='devicemodifierconf',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ahe_mb.devicemodifierconf'),
        ),
        migrations.AddField(
            model_name='devicemodifierconf',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
