# Generated by Django 5.0 on 2024-01-05 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0016_remove_device_start_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitvalue',
            options={'ordering': ('bit_map', 'start_bit')},
        ),
        migrations.AlterModelOptions(
            name='enumvalue',
            options={'ordering': ('enum', 'value')},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ('map', 'field_address')},
        ),
        migrations.AlterField(
            model_name='mapmodifier',
            name='mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod', to='ahe_mb.devicemodifierconf'),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('map', 'ahe_name')},
        ),
    ]
