# Generated by Django 5.0 on 2024-01-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0017_alter_bitvalue_options_alter_enumvalue_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('map', 'ahe_name', 'bit_map')},
        ),
    ]
