# Generated by Django 5.0 on 2024-01-09 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0018_alter_field_unique_together'),
        ('ahe_sys', '0014_keymap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='mapmodifier',
            name='mod',
        ),
        migrations.RemoveField(
            model_name='mapmodifier',
            name='map',
        ),
        migrations.RemoveField(
            model_name='map',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_max_read',
        ),
        migrations.RemoveField(
            model_name='map',
            name='map_reg',
        ),
        migrations.RemoveField(
            model_name='map',
            name='read_spaces',
        ),
        migrations.CreateModel(
            name='DeviceMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_spaces', models.BooleanField(default=False)),
                ('map_reg', models.CharField(choices=[('Coil', 'Coil'), ('Discrete Input', 'Discrete Input'), ('Input Register', 'Input Register'), ('Holding Register', 'Holding Register')], default='Holding Register', max_length=50)),
                ('map_max_read', models.IntegerField(default=120)),
                ('start_address', models.IntegerField(default=0)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_type', to='ahe_sys.devicetype')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ahe_mb.map')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceModifierConf',
        ),
        migrations.DeleteModel(
            name='MapModifier',
        ),
    ]
