# Generated by Django 5.0 on 2024-01-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0019_remove_device_mod_remove_mapmodifier_mod_and_more'),
        ('ahe_sys', '0014_keymap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='SiteDevice',
        ),
    ]
