# Generated by Django 5.0 on 2024-01-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0020_rename_device_sitedevice'),
        ('ahe_sys', '0014_keymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitvalue',
            name='bit_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ahe_mb.bitmap'),
        ),
        migrations.AlterField(
            model_name='devicemap',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ahe_sys.devicetype'),
        ),
        migrations.AlterField(
            model_name='enumvalue',
            name='enum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ahe_mb.enum'),
        ),
        migrations.AlterField(
            model_name='field',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ahe_mb.map'),
        ),
        migrations.AlterField(
            model_name='sitedevice',
            name='site_device_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ahe_mb.sitemodbusdevicesconf'),
        ),
    ]
