# Generated by Django 5.0.3 on 2024-03-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0021_alter_bitvalue_bit_map_alter_devicemap_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
