# Generated by Django 5.0.3 on 2024-04-24 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahe_mb', '0022_alter_field_description'),
        ('ahe_sys', '0021_alter_site_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedevice',
            name='site_device_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='ahe_sys.sitedevicelist'),
        ),
        migrations.DeleteModel(
            name='SiteModbusDevicesConf',
        ),
    ]
